import java.util.Arrays;

/**
 *
 *  Data Structures and Algorithm with Java - Chapter 3.1 Exercise
 *
 *  -----------------------------------------------------------------
 *  Give the next five pseudorandom numbers generated by the process
 *  described on page 113, with a = 12, b = 5, and n = 100, and 92
 *  as the seed for cur.
 *  -----------------------------------------------------------------
 *
 *  @author Mustafa Arinmis
 *  @since 19.11.2020
 *
 * */

public class Main {
    public static void main(String[] args) {

        System.out.println(Arrays.toString(randArray(92, 5)));
    }

    public static int[] randArray(int seed, int length) {
        /* return given number of random number according to seed */

        int[] arr = new int[length];
        int current = seed;
        for(int i=0; i<length; i++) {
            //PRNG formula: next = (a ∗ cur + b) % n;
            arr[i] = (12 * current + 5) % 100;
            current = arr[i];
        }
        return arr;
    }
}

